USERNAME = 'jkeitha'
SERVER_IP = '192.168.42.110'
WORKER_IP = '192.168.42.111'

VM_RAM = 1024
VM_CPU = 1
CENTOS_STREAM_9 = '../boxes/CentOS-Stream-Vagrant-9-20211111.1.x86_64.vagrant-virtualbox.box'

Vagrant.configure("2") do |config|
    config.vm.box = CENTOS_STREAM_9
    config.vm.boot_timeout = 1500
    config.vm.provider "virtualbox" do |vb|
        vb.memory = VM_RAM
        vb.cpus = VM_CPU
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.vm.define "#{USERNAME}S" do |s|
        s.vm.hostname = "#{USERNAME}S"
        s.vm.network "private_network", ip: SERVER_IP
		s.vm.provision "shell", inline: "sudo curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.0-rc1 INSTALL_K3S_EXEC='--token 12345' sudo sh -s -"
        s.vm.provider "virtualbox" do |vb|
            vb.name = "#{USERNAME}S"
        end
    end

    config.vm.define "#{USERNAME}SW" do |sw|
        sw.vm.hostname = "#{USERNAME}SW"
        sw.vm.network "private_network", ip: WORKER_IP
		sw.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=12345 sh -"
        sw.vm.provider "virtualbox" do |vb|
            vb.name = "#{USERNAME}SW"
        end
    end

end
